modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "simple_item_magnet"
version = "${version}"
displayName = "Simple Item Magnet"
authors = "Lightdrew"
description = '''
Pulls nearby items
'''
#logoFile = ""

[[dependencies.simple_item_magnet]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simple_item_magnet]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simple_item_magnet]]
modId = "architectury"
type = "required"
versionRange = "[18.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.simple_item_magnet]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.8.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "simple-item-magnet.mixins.json"
